services:
  mysql:
    image: mysql:8.0
    container_name: EliteSport
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EliteSport
      MYSQL_USER: elite
      MYSQL_PASSWORD: elitesecret

    ports:
      - "3340:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "elite", "-pelitesecret"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: